# Auto-labeling rules for PRs based on changed files

'area: ETL':
  - 'pointline/services/**'
  - 'pointline/io/**'

'area: schema':
  - 'pointline/tables/**'
  - 'docs/schemas.md'

'area: research':
  - 'research/**'
  - 'pointline/research.py'

'area: CLI':
  - 'pointline/cli/**'

'area: config':
  - 'pointline/config.py'
  - 'pyproject.toml'

'area: docs':
  - 'docs/**'
  - '*.md'

'area: tests':
  - 'tests/**'

'dependencies':
  - 'pyproject.toml'
  - 'requirements*.txt'
