# Auto-labeling rules for PRs based on changed files
# Format for actions/labeler@v5

'area: ETL':
  - changed-files:
    - any-glob-to-any-file: 'pointline/services/**'
  - changed-files:
    - any-glob-to-any-file: 'pointline/io/**'

'area: schema':
  - changed-files:
    - any-glob-to-any-file: 'pointline/tables/**'
  - changed-files:
    - any-glob-to-any-file: 'docs/schemas.md'

'area: research':
  - changed-files:
    - any-glob-to-any-file: 'research/**'
  - changed-files:
    - any-glob-to-any-file: 'pointline/research.py'

'area: CLI':
  - changed-files:
    - any-glob-to-any-file: 'pointline/cli/**'

'area: config':
  - changed-files:
    - any-glob-to-any-file: 'pointline/config.py'
  - changed-files:
    - any-glob-to-any-file: 'pyproject.toml'

'area: docs':
  - changed-files:
    - any-glob-to-any-file: 'docs/**'
  - changed-files:
    - any-glob-to-any-file: '**/*.md'

'area: tests':
  - changed-files:
    - any-glob-to-any-file: 'tests/**'

'dependencies':
  - changed-files:
    - any-glob-to-any-file: 'pyproject.toml'
  - changed-files:
    - any-glob-to-any-file: 'requirements*.txt'
